# Generated by Django 4.0 on 2022-02-05 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biomarker',
            fields=[
                ('biomarker', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('battery_level', models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('unknown', 'unknown')], default='unknown', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('online', 'online'), ('offline', 'offline'), ('unknown', 'unknown')], default='unknown', max_length=255, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('last_serviced', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_district', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_profile', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NA', 'Unknown')], default='NA', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, choices=[('HP', 'Healthcare Practitioner'), ('DE', 'Data Engineer'), ('SU', 'Super User')], default='DE', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sensorreading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.CharField(max_length=255)),
                ('biomarker', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='edodvis.biomarker')),
                ('device', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='edodvis.device')),
                ('participant', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='edodvis.participant')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='participant',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='edodvis.participant'),
        ),
        migrations.AddConstraint(
            model_name='sensorreading',
            constraint=models.UniqueConstraint(fields=('participant', 'date', 'biomarker', 'device'), name='unique reading'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('device_id', 'participant'), name='unique_device'),
        ),
    ]
