# Generated by Django 4.0 on 2022-02-05 07:35

from django.db import migrations


def create_data(apps, schema_editor):
    Biomarker = apps.get_model('edodvis', 'biomarker')
    biomarker_dict =    {
    'HEARTRATE' : {
        "name": "heart_rate",
        "unit": "bpm",
        "description": "contains heart rate of participant averaged across beats per minute in a day"
    },

    'STEPS' : {
        "name": "steps",
        "unit": "steps per day",
        "description": "contains total steps of participant in a day"
    },

    'SLEEP_DURATION' : {
        "name": "sleep_duration",
        "unit": "minutes per day",
        "description": "contains total duration of sleep time in a day"
    },

    'FORGOTTEN_MEDICATION' : {
        "name": "forgotten_medication",
        "unit": "frequency",
        "description": "contains number of times the participant forgot to take his/her medication in a day"
    },

    'FORGOTTEN_WALLET' : {
        "name": "forgotten_wallet",
        "unit": "frequency",
        "description": "contains number of times the participant forgot to take his/her wallet out in a day"
    },

    'FORGOTTEN_KEYS' : {
        "name": "forgotten_keys",
        "unit": "frequency",
        "description": "contains number of times the participant forgot to take his/her keys out in a day"
    },

    'OUTINGS' : {
        "name": "outings",
        "unit": "frequency",
        "description": "contains number of times the participant went out in a day"
    },
    
    'AWAY_FROM_HOME_DURATION' : {
        "name": "away_from_home_duration",
        "unit": "minutes per day",
        "description": "contains total duration participant spent outside his/her home in a day"
    },
    
    'FREQUENCY_OPEN_MEDBOX' : {
        "name": "frequency_open_medbox",
        "unit": "frequency",
        "description": "contains number of times the participant open the medbox in a day"
    } 
    }
    
    for value in biomarker_dict.values():
        Biomarker(biomarker=value['name'],
                  unit=value['unit'],
                  description=value['description']).save()

class Migration(migrations.Migration):

    dependencies = [
        ('edodvis', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
