# Generated by Django 4.0 on 2022-02-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edodvis', '0003_rename_id_participant_participant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='medication_required',
            field=models.IntegerField(default = 0, null=True),
        ),
    ]
