# Generated by Django 4.0 on 2022-03-12 04:35

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('edodvis', '0004_participant_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.JSONField(blank=True, null=True),
        ),

    ]


