# Generated by Django 4.0 on 2022-04-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edodvis', '0005_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='battery_level',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('unknown', 'unknown')], default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HP', 'Healthcare Practitioner'), ('DE', 'Data Engineer'), ('SU', 'Super User'), ('UN', 'Unverified')], default='UN', max_length=10),
        ),
    ]
