# Generated by Django 4.0 on 2022-04-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edodvis', '0006_alter_device_battery_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='age',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='area',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='postal_district',
        ),
        migrations.AddField(
            model_name='participant',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
